Makefile
This patch eliminates this error when running rime_dict_manager and rime_deployer:
> dyld: Library not loaded: @rpath/librime.1.dylib
According to [Dynamic Library Usage Guidelines](https://developer.apple.com/library/mac/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/DynamicLibraryUsageGuidelines.html), if users do not set `DYLD_LIBRARY_PATH` properly when no useful run-path search path is set, they cannot run those two binary files successfully. I've also tested with the latest official release. Running the following commands shows that rpath is empty:
```sh
otool -l /Library/Input\ Methods/Squirrel.app/Contents/MacOS/rime_dict_manager | grep -C3 LC_RPATH
otool -l /Library/Input\ Methods/Squirrel.app/Contents/MacOS/rime_deployer | grep -C3 LC_RPATH
```
Although …
=> Fix: Add missing run-path search paths for binary files.

SquirrelInputController.m
The issue of address bar in Chrome does not exist anymore (version 47), and this old fix cause another issue that could not commit text when switching input methods in Mac (tested in Mavericks & Yosemite).
=> comment out the old fix that no longer needed.

README.md
It can't use release badge for no release exist but tags
=> chore(docs): turn version using tag badge

Squirrel.xcodeproj/project.pbxproj
* On Xcode11 Squirrel.app sign error with message "code object is not signed at all"
fix #370
=> fix(build): fix codesign error on Xcode11

Info.plist
Enable `TICapsLockLanguageSwitchCapable` to use CapsLock the native way
Closes #375
=> feat(Info.plist): enable TICapsLockLanguageSwitchCapable

Makefile, Squirrel.xcodeproj/project.pbxproj
* the new opencc dictionary files are with extension .ocd2
Old files:
New files:
=> build: copy opencc .ocd2 files

SquirrelPanel.m
In this PR we support overriding `comment_font` in style config
```yaml
font_point: 16 # default font size
"style/comment_font_point": 12 # the font size of candidate comments
"style/comment_font_face": PingFangTC # the font face of candidate comments
```
A use case of `comment_font_point` is to customize the comments of 倉頡 input methods
**Current default**
**This PR**
=> configurable comment_font_{face,point} 

input_source.m
Fixes warnings from `-Wshorten-64-to-32`:
https://travis-ci.org/github/rime/squirrel/builds/758070376#L1120
=> fix: avoid implicit lossy integer transform

README.md
Bintray has been shutdown, see https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/.
=> Replace Bintray badge to GitHub releases

SquirrelPanel.m
Remove the 5px horizontal padding to text area 
Also fix the problem of having different line height due to emoji(and other rare characters) #543
=> Remove horizontal padding and fix emoji line height

SquirrelInputController.m, SquirrelPanel.h, SquirrelPanel.m
(cherry picked from commit e75aec1478fe9f9faafbc9d0062b55d5504abd62)
`style/inline_candidate` is a parallel option to `style/inline_preedit`. Four combinations are summarized as:
| | inline_candidate=true| inline_candidate=false|
|:---:|:---:|:---:|
| **inline_preedit=true** |Both selected candidate and unselected preedit are inline|No candidate inline, only preedit|
| **inline_preedit=false** |Only selected candidate inline, no unselected preedit|Blank space|
Preview:
=> Add `inlineCandidate` option

SquirrelInputController.m
這個 PR 只修錯別字。
下一個 PR 會給 preedit 當中顯示的每個漢字的注音符號引入聲介韻順序自動糾正機制。
原理很簡單：針對單個漢字的注音符號字串本身排序即可，因為它們的 unicode 排序本來就是按照聲介韻排序的。
=> Typofix: Condidiate -> Candidate.

SquirrelApplicationDelegate.m, data/squirrel.yaml
Addresses #535 
Complements rime/librime#447
https://user-images.githubusercontent.com/4469383/108610452-a9c42680-73a3-11eb-8fd8-70a9e98db7df.mov
=> Better Option Update Display

SquirrelInputController.m, data/squirrel.yaml
Change the name of US keyboard layout to the updated one (`com.apple.keylayout.ABC`) and further allow user to set default keyboard layout other than `ABC` such as `US-Extended`, which allows accented Latin characters (e.g. typing `⌥`+`u` to get `ü`, partially fixes #646 )
=> Allow customisation of default keyboard layout

SquirrelPanel.m
This should lay the ground for future UI features. By adopting `NSTextView`, we no longer directly set vertical glyphs, and the system handles emojis better, without altering line height when an Emoji appears and disappears.
Also added an option `memorize_size` for those who doesn't want the candidates panel to keep its width when hit with screen edge.
=> Use NSTextView to render text

.github/workflows/commit-ci.yml, .github/workflows/pull-request-ci.yml, .github/workflows/release-ci.yml
Upgrade Github action to v4
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
=> Upgrade GitHub action to v4

.github/workflows/commit-ci.yml, .github/workflows/pull-request-ci.yml, .github/workflows/release-ci.yml
Use macos14 runner with M1 to speed up the CI, decrease from 3m 7s to about 1m 28s.
https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/
=> chore: use macos 14 runner with M1

Squirrel.entitlements, Squirrel.xcodeproj/project.pbxproj
這將使得鼠鬚管成為第二款支援 App Sandbox 的 macOS 副廠中文輸入法（第一款是威注音）。
已經給「~/Library/Rime」目錄開了無斷存取權限，鼠鬚管存取、建立該目錄時不會需要使用者手動允許。
已經給鼠鬚管的 IMKServerConnection 開了 Sandbox 白名單。
=> Add mac app sandbox support.

SquirrelPanel.m
it happens when the panel is displayed for the first time. usually it's the ascii mode status tooltip.
calling setTextContainerInset: in drawRect: has no effect for what's being drawn. fixed by setting the inset on an ealier occasion.
=> fix(SquirrelPanel): text shown in top-left corner

.clang-format, .github/workflows/commit-ci.yml, .github/workflows/pull-request-ci.yml, .github/workflows/release-ci.yml, Makefile
Remove clang format due to we had been migrated to Swift.
- **ci: delete clang format lint step**
- **build: remove clang format target**
- **chore: remove clang format config**
=> Remove clang format

sources/MacOSKeyCodes.swift
Sometimes (e.g. in ABC Extended keyboard layout), Option + certain keys gives modifier letters, even with `NSEvent.charactersIgnoringModifiers`
For example, <kbd>⌥</kbd>+<kbd>6</kbd> gives U+02C6 "MODIFIER LETTER CIRCUMFLEX ACCENT"
Thus in these keyboard layouts, shortcuts like <kbd>⌥</kbd>+<kbd>6</kbd> will never work with Rime.
This proposal try to use raw key code before defaulting to unrecognized symbols, so that although Rime doesn't recognize U+02C6 as a key char, but instead, we use the key code of <kbd>6</kbd> for processing. 
**Testing**: It works for the stated purpose, <kbd>⌥</kbd>+<kbd>6</kbd> works in `ABC - Extended` keyboard layout.
=> Use keyCode before defaulting to unrecognized rime keycode

.github/workflows/commit-ci.yml, .github/workflows/pull-request-ci.yml, .github/workflows/release-ci.yml, action-install.sh, data/squirrel.yaml, sources/BridgingFunctions.swift, sources/SquirrelInputController.swift, sources/SquirrelPanel.swift, sources/SquirrelTheme.swift, sources/SquirrelView.swift
This PR add paging indicator.
This is an opt-in feature. User can enable it by adding:
```yaml
patch:
style/show_paging: true
```
To minimize disruption and keep compact layout, it is shown outside of candidate panel. The paging arrows will align with first candidate, and is clickable. The roundedness follows highlighted candidate corner size.
It works under all other settings. A preview under horizontal linear layout is provided here, but other layouts also works:
https://github.com/rime/squirrel/assets/4469383/02a74d1c-1e0c-4467-adfc-1b76540d34cd
=> add paging indicators

data/squirrel.yaml
This change is needed as `horizontal` has been removed since 1.0.1.
=> fix(data/squirrel.yaml): horizontal layout in preset color schemes

action-install.sh, sources/SquirrelInputController.swift
=> fix: create sessions for empty app bundle identifiers

sources/SquirrelInputController.swift
Make sure candidatePreview is trimmed only when it is legal
Fallback to empty string  when pulling out the switcher with caption as preedit text
This seems to solve the problem mentioned in #1041
=> fix(SquirrelInputController): boundary check to prevent crash
